import type { CandidateExpression } from "@art/domain";

interface BuildManualSelectionDraftInput {
  selectedText: string;
  sentence: string;
  articleId: string;
  segmentId: string;
  generatedAt: string;
}

export function buildManualSelectionDraft(input: BuildManualSelectionDraftInput): CandidateExpression {
  const expression = input.selectedText.trim();
  const normalizedForm = expression.toLowerCase();

  return {
    id: `candidate-manual-${normalizedForm.replaceAll(/\s+/g, "-")}`,
    userId: "user-1",
    articleId: input.articleId,
    segmentId: input.segmentId,
    expression,
    normalizedForm,
    type: normalizedForm === "all at once" ? "collocation" : "other",
    meaningZh: normalizedForm === "all at once" ? "一下子、同时" : "根据上下文生成的表达",
    localMeaning:
      normalizedForm === "all at once"
        ? "suddenly or together in this sentence"
        : "AI-generated local meaning for this selection",
    sentence: input.sentence,
    sentenceTranslation:
      normalizedForm === "all at once"
        ? "老师们注意到势头并不是一下子就形成的。"
        : "AI-generated sentence translation for this selection.",
    syntaxHint: normalizedForm === "all at once" ? "Adverbial phrase modifying how momentum arrived." : null,
    difficulty: normalizedForm === "all at once" ? "B1" : "B2",
    valueScore: 78,
    candidateStatus: "backup_candidate",
    statusReason: "Learner-selected text generated by manual selection mock flow.",
    occurrenceCount: 1,
    modelProvider: "mock",
    modelName: "manual-selection-mock-v1",
    promptVersion: "manual-selection-prompt-v1",
    generationVersion: "manual-selection-v1",
    generatedAt: input.generatedAt,
  };
}
